regtest=1

# password is `boss2026`
rpcauth=student:9e2a740807c433cad4e1ceba17d5a4eb$fb01f6ab01ede71d28d6c7928e1d9ebd31637a3a83bec3ae798579a7f4997e15

# admin user for coin history tool (password: history2026)
rpcauth=admin:ac1937a24c0a362ef4713659692472de$c9785e532972667da8aaae505a5d3567be966318905a149a6c6e842aec80d3f5

[regtest]
reindex=1
maxtxfee=21000000
mintxfee=0.00000001
dustrelayfee=0
txindex=1
server=1
rpcwhitelistdefault=0
rpcwhitelist=student:listunspent,getrawchangeaddress,createrawtransaction,signrawtransactionwithwallet,sendrawtransaction,getbalances,getblockcount,createwallet,importdescriptors,generatetoaddress,stop
